### ISSUE TITLE
Abort error when share is cancelled

### ISSUE THREAD

**Issue by sgtpenguin** [daviddarnes/share-button#2]
**Describe the bug**
When closing a share dialog without selecting an option an exception is thrown in Safari.
```
Uncaught runtime errors:
×
ERROR
Abort due to cancellation of share.
```

**Screenshots**
<img width="1512" alt="Screen Shot 2023-12-19 at 11 08 24 AM" src="https://github.com/daviddarnes/share-button/assets/16600959/8a2ab367-977a-45b7-a226-a26de2ac038d">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: recent/latest

**Additional context**
Possibly wrapping `navigator.share` in a `try/catch` could avoid the issue.  Untested.

See this SO thread:
https://stackoverflow.com/questions/60510383/web-share-api-navigator-share-problem-when-canceling-share-dialog-ios-and-androi

**Comment by daviddarnes** [comment]
Thanks for reporting! I am aware of this issue, but not sure how to handle it. Could wrap it in a `try/catch` but since I think it's a promise in of itself we could use a `.then()` and a `.catch()` to catch the error and surface console information for debugging:
```js
 window.navigator.share({
      title: root.title,
      text: root.title + "\n" + window.location.href
    })
    .then(() => alert('The page was shared'))
    .catch((e) => console.log(e))
```

What do you think?

**Comment by sgtpenguin** [comment]
This looks good to me.  I just tested on my end and it works as expected in Safari, logs the error, but still working and toggling properly.
